### ISSUE TITLE
Loading a video and autoplay

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/wall-of-fame#11]
**update**
We changed from:
`all hidden and autoplay on mouseover` 

to: 
`showing the first frame and autoplay on mouseover`

For now this is ok. However I would like this to evolve further.

**Wishlist:** Include animated video preview instead of static thumnail - kinda like [this discussion on stackexchange](https://stackoverflow.com/questions/7200404/how-can-i-create-a-video-preview-thumbnail) - this wish has its own [issue](https://github.com/giveth/wall-of-fame/issues/12)

**Stuff to fix:** On mobile we should also **load the thumbnail**

**Comment by deamme** [comment]
I think you're forced to watch the chosen video for itself according to the new spec: http://fame-giveth.webflow.io/. The spec just plays all the Hall of Fame videos at the same time.

**Comment by geleeroyale** [comment]
I am not sure what you mean by `I think you're forced to watch the chosen video for itself`

The autoplay in the spec can be ignored, spec is mostly about styling the view and description
