### ISSUE TITLE
Rework video preview

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/wall-of-fame#12]
Include animated video preview instead of static thumnail - kinda like this [discussion on stackexchange](https://stackoverflow.com/questions/7200404/how-can-i-create-a-video-preview-thumbnail)

**Comment by geleeroyale** [comment]
that is how it always was, but of course it is extremely heavy on the system. try loading the page on less than great internet to see.  

a better solution would be to render something like a cashed preview, but in the meantime I am happy with the way you solved it by showing a thumbnail and keeping autoplay on mouse-hover

**Comment by deamme** [comment]
Unfortunately the library only works on node environment because it uses FFmpeg.

**Comment by geleeroyale** [comment]
ok - thanks for taking a look

**Comment by deamme** [comment]
CLosing this issue because it's a lot of work for a minor thing
