### ISSUE TITLE
change from firebase

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/wall-of-fame#14]

**Comment by deamme** [comment]
From Firebase to where?

**Comment by geleeroyale** [comment]
I did not get to fill in all issues yet :-)

@maxskant wanted to look at IPFS integration

**Comment by deamme** [comment]
Ah, I see :)!

**Comment by maxskant** [comment]
It sorta sounded like someone might be working on the IPFS already? If not, I'm really more interested in that sort of backend work than the styling.

**Comment by deamme** [comment]
I'm not working on IPFS at all. I want to take the styling if you want the IPFS stuff

**Comment by geleeroyale** [comment]
I think we had the possibility to upload to IPFS in a prior version, but removed it for performance reasons. Not sure - we have to ask @eduadiez who created the wall of fame.

**Comment by maxskant** [comment]
@deamme Yeah if you'd like to focus on the styling I'm fine if you go for it. I'd probably take a bit longer than ya anyway.

**Comment by deamme** [comment]
Using IPFS will guarantee a performance overhead, unfortunately.. One solution may be using WebTorrents instead and have a server that seeds the videos. Still have the same problems as IPFS but I think it's better on performance

**Comment by geleeroyale** [comment]
wow interesting idea with webtorrents!

**Comment by VictorBjelkholm** [comment]
> removed it for performance reasons

> IPFS will guarantee a performance overhead

> IPFS but I think it's better on performance

I would be very interested on hearing some more about the performance overhead you're seeing. Maybe let's create some benchmarks and properly compare them? I would be happy to help out with a implementation that uses IPFS if you're interested, at least provide some guiding.

**Comment by deamme** [comment]
Closing in favor of https://github.com/Giveth/wall-of-fame/issues/70. We already have an IPFS node running so we should just use it.
