### ISSUE TITLE
the old normal link was removed. 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#26]
Curious about the design decision to remove the link to the video page that has the fame.giveth.io in the tool bar vs the firebase storage one

If its all the same, i would like to share the links to the wall of fame :-D But maybe there is a piece of info i dont have...

**Comment by deamme** [comment]
I actually think that the FIREBASE button is meant to be a download link and I made the WATCH button maximize the screen instead which is pretty much the same as watching a single video on another page. We could change it to link to the single video page.

**Comment by geleeroyale** [comment]
We could also **add a share button** that shares the link to the video in the wall of fame

**Comment by GriffGreen** [comment]
the big thing is that the old links no longer work :-( https://alpha.giveth.io/campaigns/Bub3WLo6jmlG8V6j/milestones/q0hNsgWAAC1QdWDE
links to http://fame.giveth.io/GivethVWOF_v2/view/-L3oP9xSP3BxBlWcUXvo

I'm happy with any solution on the UX side... as long as we keep these links live and are able to send people these links to the video... 

Since these links are hosted at giveth.io, its a nice piece of name recognition i am hoping we dont have to give up :-D

**Comment by geleeroyale** [comment]
**Links are working again**
