### ISSUE TITLE
feature request: date label on thumbnails

### ISSUE THREAD

**Issue by satyavh** [Giveth/wall-of-fame#3]
I think it would be very useful to add date labels on the thumbnails. That way we can see which video's are new and should be watched for the reward dao

**Comment by eduadiez** [comment]
I've added the date along with the title on the thumbnails header.

Although you could see more details of the video when you click on it, it is useful that this info also appears in the header.

Thanks for the suggestion and any other you have is welcome :-)

<img width="678" alt="captura de pantalla 2017-12-14 a las 18 00 03" src="https://user-images.githubusercontent.com/20141918/34005080-11bd78e4-e0fa-11e7-9822-95eea9ebf7a8.png">
