### ISSUE TITLE
We don't have IPFS and the single video pages are inaccessible

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#30]
We have links to the single videos, which are really useful when making Milestones. But there is no way currently to find that link. This is one of the links: http://fame.giveth.io/GivethVWOF_v2/view/-L3oP9xSP3BxBlWcUXvo

I think we should replace IPFS's link with the above link.... We don't have an IPFS link... so its bad to lie! 

<img width="432" alt="screen shot 2018-03-27 at 5 26 46 pm" src="https://user-images.githubusercontent.com/14945613/37977919-1802da50-31e5-11e8-8859-b6fca30ea0f3.png">

**Comment by geleeroyale** [comment]
I support that and also suggest **changing the IPFS link to a sharing link**

**Comment by deamme** [comment]
I can replace the text with "SHARE" but what about the icon? Is a cube still okay?

**Comment by geleeroyale** [comment]
Arrow was *correct* :-) Thanks @deamme
