### ISSUE TITLE
Upload page needs a button for recording a video

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#32]
Can't make a video using the site right now... :-D Def need to fix that one! 

You can start recording it, but then it doesn't have a button to stop record and upload!

**Comment by geleeroyale** [comment]
Yes - this functionality is totally broken for me - I can't even start a recording

**Comment by deamme** [comment]
Has this worked before?

**Comment by geleeroyale** [comment]
I know that camera recording worked before. I never tried screen recording. This is a good question for @eduadiez
