### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by deamme** [Giveth/wall-of-fame#40]
Wall of Fame doesn't work very well on mobile. Please report all mobile bugs including device name.
Iphone bug that I encountered:
- Videos does not even show up
- Very hard to trigger overlay and is inconsistent with the frame borders

**Comment by geleeroyale** [comment]
Works: **Android running Lineage-OS with Brave**

Mobile UX: Autoplay onClick works great. When playing, I would expect a tap on the playing video to pause the video and show the controls.

**Comment by deamme** [comment]
Fixed with the new remake
