### ISSUE TITLE
Switch to zeit.co and use Next.js

### ISSUE THREAD

**Issue by deamme** [Giveth/wall-of-fame#42]
The app as of right now uses Netlify which is mostly for Single Page Applications (SPA). It works really well with github webhooks and updates the website as soon as we merge into master. What doesn't work well is that we don't have control over the serverside of things. This leads to issues such as responding with custom meta tags described in the comments: https://github.com/Giveth/wall-of-fame/issues/33.
We can resolve this issue by moving to https://zeit.co/now and use their Next.js framework that supports serverside-rendering. This allows us to respond with custom HTML and customize meta tags so Twitter, Facebook etc. can display preview thumbnails (though we still need to get these thumbnails from existing and future videos somehow).  This is definitely a step in the right direction and should also be apparent on the main Giveth DApp.

**Comment by vojtechsimetka** [comment]
I support move to zeit.co/now . We will likely move there with the DApp as well.

**Comment by deamme** [comment]
It uses Next.js now but is on Digital Ocean. Still needs work on CI though.
