### ISSUE TITLE
The buttons dont always show up right

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#60]
<img width="433" alt="screen shot 2018-07-27 at 4 12 43 pm" src="https://user-images.githubusercontent.com/14945613/43349918-2e726b6a-91b8-11e8-8e80-8c9b5dce7c2c.png">
See the firebase is only there cause my mouse scrolled over it

**Comment by deamme** [comment]
Seems like you're still on the old version? Try clearing your cache
