### ISSUE TITLE
Can't upload camera videos

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/wall-of-fame#61]
Every time I try it just freezes... saying its uploading.. but it doesnt upload... even if i wait over night

some screen shots...

<img width="1358" alt="screen shot 2018-09-26 at 4 54 20 pm" src="https://user-images.githubusercontent.com/14945613/46209653-af31f980-c32e-11e8-9ee6-689f2affc132.png">
<img width="554" alt="screen shot 2018-09-26 at 4 54 09 pm" src="https://user-images.githubusercontent.com/14945613/46209654-af31f980-c32e-11e8-943d-b2a45f1ecb52.png">
<img width="1236" alt="screen shot 2018-09-21 at 4 53 59 pm" src="https://user-images.githubusercontent.com/14945613/46209657-afca9000-c32e-11e8-9038-e68490d32985.png">
<img width="1245" alt="screen shot 2018-09-21 at 4 53 38 pm" src="https://user-images.githubusercontent.com/14945613/46209658-afca9000-c32e-11e8-9bb0-0fa7a0b77a47.png">

**Comment by deamme** [comment]
Seems like you're still on the old version? Try clearing your browser cache

**Comment by GriffGreen** [comment]
Hmmmmmm... I hit the refresh many times... does that usually clear the cache?
<img width="1338" alt="screen shot 2018-10-01 at 2 40 10 pm" src="https://user-images.githubusercontent.com/14945613/46289011-fb2bab00-c587-11e8-93ee-314ea92a1a3f.png">
<img width="1344" alt="screen shot 2018-10-01 at 2 39 52 pm" src="https://user-images.githubusercontent.com/14945613/46289013-fb2bab00-c587-11e8-880f-34879489485d.png">

There are a lot of people that might also have this problem... is there a banner or something that can be posted with instructions for clearing your cache instructions... or would that be impossible to implement because the cache is blocking any update in the site...?

**Comment by GriffGreen** [comment]
I reopened the issue because I am not sure how to solve this problem for other people that probably have the same issue

**Comment by GriffGreen** [comment]
But man ok I finally see all the work you put into this :-D I'm sorry man I was on an old version and never got these updates! the site looks so much better!

**Comment by deamme** [comment]
Yup, I rewrote the whole thing.. btw we can't show anything for users using the old version of the site. When I announced that the new Wall of Fame was up and running I said that people should try refreshing and clearing their cache. I can remind them again, though..
