### ISSUE TITLE
Form Notice with link for 1 month experiment

### ISSUE THREAD

**Issue by Danibelle** [Giveth/wall-of-fame#62]
We'd like to conduct an experiment this month offering a form as an alternative to a video entry on the Wall of Fame. 

Initial thought was just to share in the rooms and with those receiving points directly; it's been suggested that we add the link to the Wall itself with some text, perhaps "Received points this month? Please add your video below, and/or complete this form!"

This could be accomplished with an info bar at top?

Form is found here: https://docs.google.com/forms/d/1GdJGWMivV870gAEkf0rUol_Onxt_W4FE61gdYsMh-g8/edit

**Comment by deamme** [comment]
This is now fixed. You can open the issue again if it's not sufficient.

**Comment by Danibelle** [comment]
I gave you the wrong link, so sorry.. please use this one for noneditable version

https://goo.gl/forms/allw3IgbPQ1JM6gr2
