### ISSUE TITLE
Change Week #s to Dates

### ISSUE THREAD

**Issue by Danibelle** [Giveth/wall-of-fame#63]
The "Week #" system is very difficult to translate to the RewardDAO worksheet for videos. It would be helpful to have a page per month to align with the Reward Cycle - is there any reason not to change it from weeks to months? If it's too many to a page, perhaps 1st through 15th is an option. At minimum - adding the date range to each week would alleviate confusion.

**Comment by krrisis** [comment]
@deamme

**Comment by krrisis** [comment]
I'd go for 1 month if feasible (1-31) and if not easy indeed Monday xx/xx to Sunday xx/xx

**Comment by deamme** [comment]
It's using months instead of weeks now. Let me know if it's suffecient as it is.

**Comment by Danibelle** [comment]
@deamme  all I see is "Week # - 2018"  not the month.  I did clear my cache..

Wondering if this change will reorder/sort past videos or only affect now going forward - the buttons would then become 'This Month' and 'Next Month'.

![image](https://user-images.githubusercontent.com/39466970/46982134-111d8d80-d0a9-11e8-9388-198a71a21e93.png)

**Comment by Danibelle** [comment]
Ok i've had to use private mode to get this to work properly, but it does, when I do that.

**Comment by Danibelle** [comment]
Closing this issue - while I still see the old version no matter how much cache clearing I do, the change has been implemented and seems to work for most others.
