### ISSUE TITLE
Video settings modification

### ISSUE THREAD

**Issue by Danibelle** [Giveth/wall-of-fame#64]
The enabled Autoplay functionality of the videos is very difficult to manage when copying to the RewardDAO spreadsheet - videos begin playing when touched. Not sure where this can be addressed - the problem isn't with the Wall itself, it's with copying the video links to the spreadsheet and in the Milestones created as well.

Additionally, feedback from Lindsay is that there are two places the video links can be copied from, and challenges with both:

1) Fame link provides the Eth address
2) Firebase link doesn't scroll

**Comment by krrisis** [comment]
@deamme

**Comment by deamme** [comment]
I disabled the autoplay on single video pages. Let me know if this is now fixed.

**Comment by Danibelle** [comment]
Thanks, I'll need to go through the Reward DAO process to test this when I meet with LIndsay next.
