### ISSUE TITLE
Delete 2 of my videos on the Wall of fame 

### ISSUE THREAD

**Issue by mmohorko** [Giveth/wall-of-fame#75]
I accidentally uploaded my video 3 times (please say nothing). Can you delete 2 of them and just leave one of them? Thank you. :)

**Comment by mmohorko** [comment]
After I logged into my Metamask a "delete" button appeared. I was able to delete one of the videos but for some reason, I can't delete the other one ...

**Comment by FrederikBolding** [comment]
Not sure if this is possible @deamme - Otherwise, it probably isn't that big an issue 😄 Btw, for issues like this just contact us on Riot!

**Comment by deamme** [comment]
There's only one now but I think something is bugged since your video doesn't exist anymore..

**Comment by mmohorko** [comment]
What do you suggest I should do? Should we delete the video that is now online and not playing and I upload it one more time? 

Btw - I saw this same problem also with other videos on the wall of fame.

**Comment by deamme** [comment]
The other videos is because they are in an unsupported format. Yours just doesn't exist anymore. Can you 
try upload again?

**Comment by mmohorko** [comment]
Ok I uploaded the video one more time.

**Comment by deamme** [comment]
Seems to be alright now
