### ISSUE TITLE
Remove/Replace spreadsheet option from main page

### ISSUE THREAD

**Issue by Danibelle** [Giveth/wall-of-fame#76]
Let's get rid of the spreadsheet option!  It was a time-limited solution and now we have the requirement for recipients to create their Milestone in the Dapp.  Anyone who has filled out the form up until this issue is completed will of course still receive credit.

We can replace it with a link to this GitHub Repo for people having issues so we can track manage and fix problems:

![image](https://user-images.githubusercontent.com/39466970/60830944-fed70880-a17d-11e9-9878-3def4f4107ad.png)

Change text from existing:
Received points this month? Please add your video below, and/or complete this form!

To new:
Received points in Riot? Please add your video below and embed link in your [RewardDAO Milestone](https://beta.giveth.io/campaigns/5b3d9746329bc64ae74d1424). You can report any issues to our [Github Repo](https://github.com/Giveth/wall-of-fame), Thank you for contributing to Giveth!

**Comment by iemwill** [comment]
started first work here: https://github.com/iemwill/wall-of-fame/blob/patch-1/pages/index.js
lines 169-172.
