### ISSUE TITLE
Upload new wof entry doesnt work on brave+firefox

### ISSUE THREAD

**Issue by iemwill** [Giveth/wall-of-fame#78]
Hei!

As mentioned in the riot contributors room i got a problem to generate a new wall of fame card.

Got a little bit further, but now after selecting the video after clicking updload they saysin im not connected to my metamask account but they dont ask to connect...

![grafik](https://user-images.githubusercontent.com/33894930/60885787-b2103200-a250-11e9-9573-ae45ab572af9.png)

**Comment by iemwill** [comment]
Same on Firefox:
![image](https://user-images.githubusercontent.com/33894930/60888545-51d0be80-a257-11e9-930b-bc6e32563ebe.png)

**Comment by FrederikBolding** [comment]
I don't have time at the moment, but will look at this eventually, if no one else jumps on it! Thanks for reporting @iemwill

**Comment by FrederikBolding** [comment]
I'm looking into this now, I seem to have found the issue!
